# Generated by Django 4.2.7 on 2023-11-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, default='', max_length=3000, null=True, verbose_name='Comments')),
                ('invoice_number', models.IntegerField(unique=True, verbose_name='Invoice Number')),
                ('invoice_date', models.DateField(verbose_name='Invoice Date')),
                ('name', models.CharField(default='', max_length=120, verbose_name='Customer Name')),
                ('item_one', models.CharField(default='', max_length=200, verbose_name='Item 1')),
                ('item_one_quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('item_one_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=500000, verbose_name='Unit Price (€)')),
                ('item_one_total_price', models.DecimalField(decimal_places=2, default=0, max_digits=500000, verbose_name='Total (€)')),
                ('item_two', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Item 2')),
                ('item_two_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('item_two_unit_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=500000, null=True, verbose_name='Unit Price (€)')),
                ('item_two_total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=500000, null=True, verbose_name='Total (€)')),
                ('item_three', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Item 3')),
                ('item_three_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('item_three_unit_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=500000, null=True, verbose_name='Unit Price (€)')),
                ('item_three_total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=500000, null=True, verbose_name='Total (€)')),
                ('item_four', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Item 4')),
                ('item_four_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('item_four_unit_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=500000, null=True, verbose_name='Unit Price (€)')),
                ('item_four_total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=500000, null=True, verbose_name='Total (€)')),
                ('item_five', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Item 5')),
                ('item_five_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('item_five_unit_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=500000, null=True, verbose_name='Unit Price (€)')),
                ('item_five_total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=500000, null=True, verbose_name='Total (€)')),
                ('phone_number', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=5000000, verbose_name='Invoice Total (€)')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5000000, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('invoice_type', models.CharField(choices=[('Receipt', 'Receipt'), ('Proforma Invoice', 'Proforma Invoice'), ('Invoice', 'Invoice')], default='', max_length=50)),
            ],
        ),
    ]
